version: '3.8'

services:
  valida-cfdi-landing-page:
    build: .
    container_name: valida-cfdi-landing-page
    ports:
      - "8087:80"
    # volumes:
    #   - .:/usr/share/nginx/html
    restart: always
    networks:
      - web_network # Une el servicio a la red del proxy

networks:
  web_network:
    external: true # Indica que la red ya existe y no debe crearla de nuevo
